services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravel

  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    environment:
      - TZ=Europe/Vilnius
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/logs:/var/log/asterisk
      - ./asterisk/lib:/var/lib/asterisk
    ports:
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "8088:8088/tcp"
      - "10000-20000:10000-20000/udp"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
